update pull 100 to make storage halfway through

diff --git a/.github/workflows/pull-one-hundred.yml b/.github/workflows/pull-one-hundred.yml
--- a/.github/workflows/pull-one-hundred.yml
+++ b/.github/workflows/pull-one-hundred.yml
@@ -78,60 +78,106 @@ jobs:
       - name: Pull Docker Hub Images (Second Round)
         run: |
           images=(
-            "rockylinux/rockylinux"
-            "fedora"
-            "archlinux"
-            "clearlinux/stable"
-            "oraclelinux"
-            "centos"
-            "opensuse/leap"
-            "opensuse/tumbleweed"
-            "tensorflow/tensorflow"
-            "pytorch/pytorch"
-            "jupyter/scipy-notebook"
-            "jupyter/base-notebook"
-            "jupyter/minimal-notebook"
-            "apache/airflow"
-            "confluentinc/cp-kafka"
-            "confluentinc/cp-zookeeper"
-            "confluentinc/cp-schema-registry"
-            "confluentinc/cp-kafka-connect"
-            "minio/minio"
-            "selenium/standalone-chrome"
-            "selenium/standalone-firefox"
-            "bitnami/zookeeper"
-            "bitnami/wordpress"
-            "bitnami/drupal"
-            "bitnami/magento"
-            "portainer/portainer-ce"
-            "linuxserver/plex"
-            "linuxserver/jellyfin"
-            "linuxserver/swag"
-            "linuxserver/qbittorrent"
-            "linuxserver/sonarr"
-            "linuxserver/radarr"
-            "linuxserver/lidarr"
-            "docker:dind"
-            "docker:latest"
-            "docker/compose"
-            "hello-world"
-            "hashicorp/terraform"
-            "hashicorp/vault"
-            "hashicorp/consul"
-            "circleci/node"
-            "circleci/python"
-            "circleci/golang"
-            "circleci/openjdk"
-            "circleci/ruby"
-            "circleci/php"
-            "circleci/mysql"
-            "circleci/postgres"
-            "circleci/mongo"
-            "circleci/redis"
-            "circleci/nginx"
-            "circleci/docker"
-            "amazonlinux"
-            )
+            "alpine"
+            "ubuntu"
+            "nginx"
+            "redis"
+            "postgres"
+            "node"
+            "python"
+            "golang"
+            "mongo"
+            "mysql"
+            "busybox"
+            "httpd"
+            "debian"
+            "traefik"
+            "elasticsearch"
+            "logstash"
+            "kibana"
+            "vault"
+            "consul"
+            "haproxy"
+            "php"
+            "ruby"
+            "openjdk"
+            "tomcat"
+            "influxdb"
+            "grafana/grafana"
+            "prom/prometheus"
+            "prom/alertmanager"
+            "telegraf"
+            "zookeeper"
+            "cassandra"
+            "rabbitmq"
+            "bitnami/nginx"
+            "bitnami/mariadb"
+            "bitnami/redis"
+            "bitnami/postgresql"
+            "bitnami/mongodb"
+            "bitnami/jenkins"
+            "bitnami/grafana"
+            "bitnami/prometheus"
+            "bitnami/apache"
+            "bitnami/minio"
+            "bitnami/kafka"
+           )
+          for image in "${images[@]}"; do
+            echo "Pulling $image..."
+            docker pull "docker.io/$image" || echo "Failed to pull $image — skipping."
+          done
+
+      - name: Remove Images to make space
+        run: |
+          docker image prune -a -f
+
+      - name: Pull Docker Hub Images (Third Round)
+        run: |
+          images=(
+            "alpine"
+            "ubuntu"
+            "nginx"
+            "redis"
+            "postgres"
+            "node"
+            "python"
+            "golang"
+            "mongo"
+            "mysql"
+            "busybox"
+            "httpd"
+            "debian"
+            "traefik"
+            "elasticsearch"
+            "logstash"
+            "kibana"
+            "vault"
+            "consul"
+            "haproxy"
+            "php"
+            "ruby"
+            "openjdk"
+            "tomcat"
+            "influxdb"
+            "grafana/grafana"
+            "prom/prometheus"
+            "prom/alertmanager"
+            "telegraf"
+            "zookeeper"
+            "cassandra"
+            "rabbitmq"
+            "bitnami/nginx"
+            "bitnami/mariadb"
+            "bitnami/redis"
+            "bitnami/postgresql"
+            "bitnami/mongodb"
+            "bitnami/jenkins"
+            "bitnami/grafana"
+            "bitnami/prometheus"
+            "bitnami/apache"
+            "bitnami/minio"
+            "bitnami/kafka"
+           )
           for image in "${images[@]}"; do
             echo "Pulling $image..."
             docker pull "docker.io/$image" || echo "Failed to pull $image — skipping."
